# Generated by Django 4.2.2 on 2023-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_band_member_singer_member_singer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symmetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ManyToManyField(to='inventory.symmetric')),
            ],
        ),
        migrations.CreateModel(
            name='AsSymmetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ManyToManyField(to='inventory.assymmetric')),
            ],
        ),
    ]
