# Generated by Django 4.2.2 on 2023-06-21 16:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_mytest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytest',
            options={'base_manager_name': 'objects', 'default_manager_name': 'manager'},
        ),
        migrations.AlterModelManagers(
            name='mytest',
            managers=[
                ('manager', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
