# Generated by Django 4.2.2 on 2023-06-21 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_mytest_options_alter_mytest_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['when', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.question')),
            ],
            options={
                'order_with_respect_to': 'quest',
            },
        ),
    ]
