# Generated by Django 4.2.2 on 2023-06-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_question_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField(unique=True)),
                ('content', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['page_num'], name='what_page')],
            },
        ),
    ]
