# Generated by Django 4.2.2 on 2023-06-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_bookpages_what_page_bookpages_desc_page_num'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookpages',
            name='desc_page_num',
        ),
        migrations.AddIndex(
            model_name='bookpages',
            index=models.Index(models.OrderBy(models.F('page_num')), name='desc_page_num'),
        ),
    ]
