# Generated by Django 4.2.2 on 2023-06-22 23:38

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_remove_bookpages_desc_page_num_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookpages',
            name='desc_page_num',
        ),
        migrations.AddIndex(
            model_name='bookpages',
            index=models.Index(django.db.models.expressions.CombinedExpression(models.F('page_num'), '^', models.Value(2)), name='mul_page_num'),
        ),
    ]
