# Generated by Django 4.2.2 on 2023-06-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_alter_bookpages_page_num'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookpages',
            index=models.Index(fields=['content'], include=('page_num',), name='inc_page_num'),
        ),
    ]
