# Generated by Django 4.2.2 on 2023-06-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_bookpages_inc_page_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.IntegerField()),
                ('field2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='uniquemodel',
            constraint=models.UniqueConstraint(models.F('field1'), models.F('field2'), name='unique_fields_constraint'),
        ),
    ]
