# Generated by Django 4.2.2 on 2023-06-23 16:25

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_uniquemodel_uniquemodel_unique_fields_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uniquemodel',
            name='unique_fields_constraint',
        ),
        migrations.AddConstraint(
            model_name='uniquemodel',
            constraint=models.UniqueConstraint(models.OrderBy(django.db.models.functions.text.Lower('field1'), descending=True), models.F('field2'), name='unique_fields_constraint'),
        ),
    ]
