# Generated by Django 4.2.2 on 2023-06-24 21:46

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_client'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookpages',
            index=models.Index(django.db.models.functions.text.Lower('content'), name='lower_content'),
        ),
    ]
