# Generated by Django 4.2.2 on 2023-06-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_bookpages_lower_content'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookpages',
            name='lower_content',
        ),
        migrations.AddIndex(
            model_name='bookpages',
            index=models.Index(models.OrderBy(models.F('content'), descending=True), name='lower_content'),
        ),
    ]
