# Generated by Django 4.2.2 on 2023-06-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_remove_bookpages_lower_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
            ],
        ),
    ]
