# Generated by Django 4.2.2 on 2023-07-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_author_blog_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='number_of_comments',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='number_of_pingbacks',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='rating',
        ),
    ]
