# Generated by Django 4.2.2 on 2023-07-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_remove_entry_body_text_remove_entry_mod_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='inventory.blog'),
        ),
    ]
