# Generated by Django 4.2.1 on 2023-07-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('pub', 'published'), ('unpub', 'unpublished')], default='pub', max_length=5),
        ),
    ]
