# Generated by Django 4.2.2 on 2023-07-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_book_date_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='commentors',
            field=models.ManyToManyField(blank=True, null=True, to='myadmin.commentors'),
        ),
    ]
