# Generated by Django 4.2.2 on 2023-06-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='colour',
            field=models.CharField(choices=[('RD', 'Red'), ('BL', 'Blue')], max_length=50),
        ),
    ]
