# Generated by Django 4.2.2 on 2023-07-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
